---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: web-app
  namespace: default
spec:
  interval: 30s
  ref:
    branch: main
  url: ssh://git@github.com:22/JaroslawCzerwinski/FluxCD.git
  secretRef:
    name:  web-app-auth
